### ISSUE TITLE
Make filters more intuitive to use

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozwebqa-dashboard#52]
Let's use the sidebar for the filters to give more space for the issues/pulls. This would also be an opportunity to revise the filters, such as a toggles for assigned and unassigned (instead of a dropdown). It would also be neat to have a link to clear all filters. Feel free to bump these to a separate issue.

**Comment by justinpotts** [comment]
Currently, since we're using the dashboard as a page template, and then having the content of the dashboard update dynamically, I'm not sure of a way to integrate the filters into the sidebar, since they're going to change with each page. 

I can however add the "clear all filters" and make the filters more intuitive.
